### ISSUE TITLE
I have installed this connector but it does not work

### ISSUE THREAD

**Issue by bigoss** [OCA/connector-prestashop#116]
Hello,

Not sure this is an issue or somthing that i'am missing.
Have successfully installed it does connect to PS DB but does not import anything can anyone help? on sync base data it warns : An ERP record with same ID already exists on PrestaShop

**Comment by pedrobaeza** [comment]
Please put server log of the error and Odoo version

**Comment by bigoss** [comment]
Odoo 10 
I had logs disabled now enabled logs but odoo does not work anymore output below

2019-04-09 07:20:00,115 1732 INFO pepiki odoo.modules.loading: loading 1 modules...
2019-04-09 07:20:00,129 1732 INFO pepiki odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries
2019-04-09 07:20:00,170 1732 INFO pepiki odoo.modules.loading: loading 59 modules...
2019-04-09 07:20:00,174 1732 WARNING pepiki odoo.modules.loading: Transient module states were reset
2019-04-09 07:20:00,174 1732 ERROR pepiki odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/opt/odoo/odoo/modules/registry.py", line 83, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo/modules/loading.py", line 373, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo/modules/loading.py", line 270, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo/modules/loading.py", line 147, in load_module_graph
    model_names = registry.load(cr, package)
  File "/opt/odoo/odoo/modules/registry.py", line 268, in load
    model = cls._build_model(self, cr)
  File "/opt/odoo/odoo/models.py", line 531, in _build_model
    raise TypeError("Model %r does not exist in registry." % name)
TypeError: Model 'ir.qweb.field.float' does not exist in registry.

**Comment by pedrobaeza** [comment]
This is not something related to the connector, but your deployment in general. It can fail in this module or any other. Please check proper Odoo installation methods.

**Comment by bigoss** [comment]
Thank you 

I know , my odoo stopped to work for some reason.
But with working odoo I had problems on sync base data  : An ERP record with same ID already exists on PrestaShop.

Have reinstalled odoo now. 
I am wondering what is the best way to install connector with all dependencies. 
There is not much details about installation in README.md
