### ISSUE TITLE
connector related problem using odoo 11, can't import 

### ISSUE THREAD

**Issue by thaiger14** [OCA/connector-prestashop#139]
I am not sure if I can ask for help here, but I have a problem relating the connector, I am using ubuntu 16.04 and odoo 11 ce. I setup with web service of prestashop 1.6.1.24 and 1.7.6.3. And both of them got error as output when I try to import the products. Below are the log from odoo, thank you.

Error:
 Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 653, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 695, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 699, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 690, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-299>", line 2, in import_prestashop
  File "/opt/odoo/odoo11/odoo/api.py", line 379, in loop
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo11/odoo/api.py", line 379, in <listcomp>
    result = [method(rec, *args, **kwargs) for rec in self]
  File "/opt/odoo/odoo11-custom-addons/prestashop_connector/wizard/prestashop_connector_wizard.py", line 130, in import_prestashop
    self.shop_ids.update_prestashop_category()
  File "/opt/odoo/odoo11-custom-addons/prestashop_connector/models/sale_shop.py", line 2430, in update_prestashop_category
    prestashop = PrestaShopWebServiceDict(shop.prestashop_instance_id.location,shop.prestashop_instance_id.webservice_key,physical_url = shop.shop_physical_url or None)
  File "/opt/odoo/odoo11-custom-addons/prestashop_connector/prestapyt/prestapyt.py", line 120, in __init__
    if not self._api_url.endswith('/'):
AttributeError: 'bool' object has no attribute 'endswith'

**Comment by pedrobaeza** [comment]
You haven't configured the API URL in the connector definition.

**Comment by thaiger14** [comment]
Hi, Pedrobaeza
Can you help to specify where I can insert the API URL in the connector? Thank you very much!

**Comment by pedrobaeza** [comment]
It's supposed that there's an entry in the connector menu, but I can't tell you more right now.
