### ISSUE TITLE
While Migrating the server I am facing this error as soon as I include the module.

### ISSUE THREAD

**Issue by DonFeraRRi** [OCA/connector-prestashop#144]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 193, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 181, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/service/server.py", line 307, in app
    return self.app(e, s)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 186, in application
    return application_unproxied(environ, start_response)
  File "/opt/odoo/odoo/service/wsgi_server.py", line 172, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo/http.py", line 1325, in __call__
    self.load_addons()
  File "/opt/odoo/odoo/http.py", line 1346, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/opt/odoo/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/opt/odoo/addons/connector_prestashop/__init__.py", line 6, in <module>
    import consumer
  File "/opt/odoo/addons/connector_prestashop/consumer.py", line 9, in <module>
    from .models.product_template.exporter import export_inventory
  File "/opt/odoo/addons/connector_prestashop/models/__init__.py", line 4, in <module>
    from . import binding
  File "/opt/odoo/addons/connector_prestashop/models/binding/__init__.py", line 4, in <module>
    from . import common
  File "/opt/odoo/addons/connector_prestashop/models/binding/common.py", line 6, in <module>
    from ...unit.importer import import_record
  File "/opt/odoo/addons/connector_prestashop/unit/__init__.py", line 11, in <module>
    import backend_adapter
  File "/opt/odoo/addons/connector_prestashop/unit/backend_adapter.py", line 51, in <module>
    class PrestaShopWebServiceImage(PrestaShopWebServiceDict):
NameError: name 'PrestaShopWebServiceDict' is not defined

**Comment by flotho** [comment]
prestapyt changed its structure recently. this class is no more present in recent versions.
So I recommend you to refactor the code of connector_prestashop to match the new prestapyt structure.
