### ISSUE TITLE
Bug while exporting products from Odoo

### ISSUE THREAD

**Issue by mcassuto** [OCA/connector-prestashop#32]
Using the module connector_prestashop_catalog_manager, when exporting products, most of the product_product and product_variant are transferred.

Over a total of 1500 products, 12 have not been transferred; the job is showing the following error: 

Task
openerp.addons.connector_prestashop.unit.exporter.export_record('prestashop.product.template', 2, {'list_price': 12.55})
Job Function
openerp.addons.connector_prestashop.unit.exporter.export_record 
Channel
root.prestashop

Traceback (most recent call last):
  File "/home/odoo8dev/git/connector/connector/controllers/main.py", line 90, in runjob
    self._try_perform_job(session_hdl, job)
  File "/home/odoo8dev/git/connector/connector/controllers/main.py", line 66, in _try_perform_job
    job.perform(session)
  File "/home/odoo8dev/git/connector/connector/queue/job.py", line 512, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/home/odoo8dev/git/connector-prestashop/connector_prestashop/unit/exporter.py", line 198, in export_record
    return exporter.run(binding_id, fields=fields)
  File "/home/odoo8dev/git/connector-prestashop/connector_prestashop/unit/exporter.py", line 48, in run
    result = self._run(*args, **kwargs)
  File "/home/odoo8dev/git/connector-prestashop/connector_prestashop/unit/exporter.py", line 126, in _run
    self._update(record)
  File "/home/odoo8dev/git/connector-prestashop/connector_prestashop_catalog_manager/product.py", line 138, in _update
    self.backend_adapter.write(self.prestashop_id, data)
  File "/home/odoo8dev/git/connector-prestashop/connector_prestashop/unit/backend_adapter.py", line 185, in write
    self._prestashop_model, {self._export_node_name: attributes})
  File "/home/odoo8dev/git/client/tools/eggs/prestapyt-0.7.0-py2.7.egg/prestapyt/prestapyt.py", line 385, in edit
    return self.edit_with_url(full_url, content)
  File "/home/odoo8dev/git/client/tools/eggs/prestapyt-0.7.0-py2.7.egg/prestapyt/prestapyt.py", line 579, in edit_with_url
    return _super.edit_with_url(url, xml_content)
  File "/home/odoo8dev/git/client/tools/eggs/prestapyt-0.7.0-py2.7.egg/prestapyt/prestapyt.py", line 396, in edit_with_url
    response = self._execute(url, 'PUT', data=content, add_headers=headers)
  File "/home/odoo8dev/git/client/tools/eggs/prestapyt-0.7.0-py2.7.egg/prestapyt/prestapyt.py", line 210, in _execute
    self._check_status_code(response.status_code, response.content)
  File "/home/odoo8dev/git/client/tools/eggs/prestapyt-0.7.0-py2.7.egg/prestapyt/prestapyt.py", line 155, in _check_status_code
    ps_error_code, ps_error_msg = self._parse_error(content)
  File "/home/odoo8dev/git/client/tools/eggs/prestapyt-0.7.0-py2.7.egg/prestapyt/prestapyt.py", line 122, in _parse_error
    error_answer = self._parse(xml_content)
  File "/home/odoo8dev/git/client/tools/eggs/prestapyt-0.7.0-py2.7.egg/prestapyt/prestapyt.py", line 588, in _parse
    parsed_content = super(PrestaShopWebServiceDict, self)._parse(content)
  File "/home/odoo8dev/git/client/tools/eggs/prestapyt-0.7.0-py2.7.egg/prestapyt/prestapyt.py", line 234, in _parse
    (e, content[:512])
PrestaShopWebServiceError: 'HTTP XML response is not parsable : undefined entity: line 57, column 26. <!DOCTYPE HTML>\n\n\n\n\n<html lang="fr-ca"  class="default" >\n\t    \n\t<head>\n\t\t<meta charset="utf-8" />\n\t\t<title>Erreur 404 - mysite </title>\n\t\t\t\t\t<meta name="description" content="Impossible de trouver la page"'

**Comment by pedrobaeza** [comment]
This shouldn't be put as an issue, as there's an opened PR. This seems to be on your side, as there's a 404 error page, probably because the product is not found.

**Comment by mcassuto** [comment]
Thanks @pedrobaeza we will have a look at our prestashop provider.
Please keep it open, I will post the answer here; it may help someone else.

**Comment by pedrobaeza** [comment]
Well, closed issues are also searchable, so I prefer to keep it closed, because it's not actually an issue.
