### ISSUE TITLE
Problem with data export

### ISSUE THREAD

**Issue by bodi000** [OCA/connector-prestashop#39]
Hello,

i hope this is the right place.. I try to use v7 and I get this when trying to export. I noticed that the same code is ported up to v10. Am I missing something?

Thank you
Bogdan

Traceback (most recent call last):
  File "/opt/openerp/7.0/extra-addons/connector/queue/worker.py", line 123, in run_job
    job.perform(session)
  File "/opt/openerp/7.0/extra-addons/connector/queue/job.py", line 537, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/opt/openerp/7.0/extra-addons/prestashoperpconnect/unit/export_synchronizer.py", line 205, in export_record
    return exporter.run(binding_id, fields=fields)
  File "/opt/openerp/7.0/extra-addons/prestashoperpconnect/unit/export_synchronizer.py", line 79, in run
    result = self._run(*args, **kwargs)
  File "/opt/openerp/7.0/extra-addons/prestashoperpconnect/unit/export_synchronizer.py", line 145, in _run
    self._map_data(fields=fields)
  File "/opt/openerp/7.0/extra-addons/prestashoperpconnect/unit/export_synchronizer.py", line 175, in _map_data
    self.mapper.convert(self.get_record_by_lang(), fields=fields)
  File "/opt/openerp/7.0/extra-addons/prestashoperpconnect/unit/mapper.py", line 735, in convert
    self._convert(records_by_language[first_key], fields=fields)
AttributeError: 'ProductExportMapper' object has no attribute '_convert'

**Comment by pedrobaeza** [comment]
Closing as discussed in next issue.
