### ISSUE TITLE
[7.0] jobs not executed due to wrong spelling of PS webservice ressource 'order_slip'

### ISSUE THREAD

**Issue by bodi000** [OCA/connector-prestashop#42]
While executing jobs like:
 openerp.addons.prestashoperpconnect.unit.import_synchronizer.import_refunds(1, None) 
the following traceback is generated:

Traceback (most recent call last):
  File "/opt/openerp/7.0/extra-addons/connector/queue/worker.py", line 123, in run_job
    job.perform(session)
  File "/opt/openerp/7.0/extra-addons/connector/queue/job.py", line 537, in perform
    self.result = self.func(session, *self.args, **self.kwargs)
  File "/opt/openerp/7.0/extra-addons/prestashoperpconnect/unit/import_synchronizer.py", line 1123, in import_refunds
    import_batch(session, 'prestashop.refund', backend_id, filters)
  File "/opt/openerp/7.0/extra-addons/prestashoperpconnect/unit/import_synchronizer.py", line 1011, in import_batch
    importer.run(filters=filters, **kwargs)
  File "/opt/openerp/7.0/extra-addons/prestashoperpconnect/unit/import_synchronizer.py", line 183, in run
    record_ids = self._run_page(filters, **kwargs)
  File "/opt/openerp/7.0/extra-addons/prestashoperpconnect/unit/import_synchronizer.py", line 191, in _run_page
    record_ids = self.backend_adapter.search(filters)
  File "/opt/openerp/7.0/extra-addons/prestashoperpconnect/unit/backend_adapter.py", line 126, in search
    return api.search(self._prestashop_model, filters)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 493, in search
    search(resource, options=options)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 321, in search
    return self.get(resource, options=options)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 339, in get
    return self.get_with_url(full_url)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 512, in get_with_url
    response = super(PrestaShopWebServiceDict, self).get_with_url(url)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 348, in get_with_url
    return self._parse(self._execute(url, 'GET').content)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 210, in _execute
    self._check_status_code(response.status_code, response.content)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 160, in _check_status_code
    ps_error_code=ps_error_code,
PrestaShopWebServiceError: 'Resource of type "order_slips" does not exists. Did you mean: "order_slip"? The full list is: "addresses", "carriers", "cart_rules", "carts", "categories", "combinations", "configurations", "contacts", "content_management_system", "countries", "currencies", "customer_messages", "customer_threads", "customers", "customizations", "deliveries", "employees", "groups", "guests", "image_types", "images", "languages", "manufacturers", "order_carriers", "order_details", "order_discounts", "order_histories", "order_invoices", "order_payments", "order_slip", "order_states", "orders", "price_ranges", "product_customization_fields", "product_feature_values", "product_features", "product_option_values", "product_options", "product_suppliers", "products", "search", "shop_groups", "shop_urls", "shops", "specific_price_rules", "specific_prices", "states", "stock_availables", "stock_movement_reasons", "stock_movements", "stocks", "stores", "suppliers", "supply_order_details", "supply_order_histories", "supply_order_receipt_histories", "supply_order_states", "supply_orders", "tags", "tax_rule_groups", "tax_rules", "taxes", "translated_configurations", "warehouse_product_locations", "warehouses", "weight_ranges", "zones"'

the statement `_prestashop_model = 'order_slips'` should be `_prestashop_model = 'order_slip'`, due to an incoherence in PS.

**Comment by pedrobaeza** [comment]
This is because PS renamed in one version (1.6.x the models to plural), but the rest of the versions are again singular.  We needed to treat that version separately in the v8 and v9 connector. 

Closing this as there's a PR in course.
