### ISSUE TITLE
Connector installation issue Google Drive

### ISSUE THREAD

**Issue by dstemple67** [OCA/connector-prestashop#60]
Here is the traceback - it's taking issue with a Google Drive record when installing.

Odoo Server Error
Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 319, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 312, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 962, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/web/controllers/main.py", line 901, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/web/controllers/main.py", line 889, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/module/module.py", line 459, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/module/module.py", line 533, in _button_immediate_function
    registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 338, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 237, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/modules/loading.py", line 98, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/convert.py", line 851, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/convert.py", line 938, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/convert.py", line 801, in parse
    self.parse(rec, mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/convert.py", line 804, in parse
    self._tags[rec.tag](self.cr, rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/tools/convert.py", line 708, in _tag_record
    id = self.pool['ir.model.data']._update(cr, self.uid, rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode, context=rec_context )
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/base/ir/ir_model.py", line 1143, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/connector/producer.py", line 48, in create
    record_id = create_original(self, vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 4151, in create
    record = self.browse(self._create(old_vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/models.py", line 4289, in _create
    tuple([u[2] for u in updates if len(u) > 2])
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/sql_db.py", line 220, in execute
    res = self._obj.execute(query, params)
ParseError: "duplicate key value violates unique constraint "ir_config_parameter_key_uniq"
DETAIL:  Key (key)=(google_drive_client_id) already exists.
" while parsing /opt/bitnami/apps/odoo/lib/odoo-9.0rc20160620-py2.7.egg/openerp/addons/google_drive/google_drive_data.xml:5, near
<record id="config_google_drive_client_id" model="ir.config_parameter">
            <field name="key">google_drive_client_id</field>
            <field name="value">598905559630.apps.googleusercontent.com</field>
            <field name="group_ids" eval="[(4, ref('base.group_system'))]"/>
        </record>

I appreciate your efforts. this looks like a great connector!

**Comment by pedrobaeza** [comment]
This has nothing to do with the connector, but with the other module.

**Comment by dstemple67** [comment]
The Google Drive integration then. What would cause an inspection of the Google Drive key, none of the other dozens of apps have thrown this error? Is that an error you have encountered before? Thanks for your help!

**Comment by pedrobaeza** [comment]
It happens after uninstalling the module and installing it again. Just remove that system parameter.

**Comment by dstemple67** [comment]
Fantastic, thank you, sir
