### ISSUE TITLE
odoo server error PrestaShopWebServiceError: 'HTTP XML response is not parsable : not well-formed (invalid token)

### ISSUE THREAD

**Issue by Stefano7777777** [OCA/connector-prestashop#74]
hi, i've just installed connector, it give me Connection successful but when i Synchronize Metadata or base data it give me this error can anyone help me please?

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/connector_prestashop/models/prestashop_backend/common.py", line 146, in synchronize_metadata
    import_batch(session, model, backend.id)
  File "/opt/odoo/addons/connector_prestashop/unit/importer.py", line 507, in import_batch
    return importer.run(filters=filters, **kwargs)
  File "/opt/odoo/addons/connector_prestashop/unit/importer.py", line 305, in run
    record_ids = self._run_page(filters, **kwargs)
  File "/opt/odoo/addons/connector_prestashop/unit/importer.py", line 313, in _run_page
    record_ids = self.backend_adapter.search(filters)
  File "/opt/odoo/addons/connector_prestashop/unit/backend_adapter.py", line 174, in search
    return self.client.search(self._prestashop_model, filters)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 521, in search
    PrestaShopWebServiceDict, self).search(resource, options=options)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 350, in search
    return self.get(resource, options=options)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 367, in get
    return self.get_with_url(full_url)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 540, in get_with_url
    response = super(PrestaShopWebServiceDict, self).get_with_url(url)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 375, in get_with_url
    return self._parse(self._execute(url, 'GET').content)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 616, in _parse
    parsed_content = super(PrestaShopWebServiceDict, self)._parse(content)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 244, in _parse
    (e, content[:512])
PrestaShopWebServiceError: 'HTTP XML response is not parsable : not well-formed (invalid token): line 48, column 105. <!DOCTYPE html>\n\n<html xmlns:fb="http://ogp.me/ns/fb#">\n<head>\n    <meta content="text/html; charset=utf-8" http-equiv="Content-Type">\n    <meta name="HandheldFriendly" content="True">\n    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">\n    <meta name="format-detection" content="telephone=no">\n    <meta property="robots" content="noindex,nofollow">\n\n    <link type="text/css" rel="stylesheet" href="http://d2vdd8rzfx5'

**Comment by pedrobaeza** [comment]
It seems something on your PrestaShop, but not with the module. You can see that the response is not correct and thus Odoo can't do anything.

Check again your connection parameters, your PS permissions, and any possible plugin that modifies the answer of the API.
