### ISSUE TITLE
Odoo Server Error PrestaShopWebServiceError: 'HTTP XML response is not parsable

### ISSUE THREAD

**Issue by Stefano7777777** [OCA/connector-prestashop#75]
hi,
i've just installed odoo connector, it connect to my prestashop but when i click on synchronize metadata it give me this:

i'm on ubuntu on localhost can anyone help me please

Odoo Server Error
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 887, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 381, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons/connector_prestashop/models/prestashop_backend/common.py", line 146, in synchronize_metadata
    import_batch(session, model, backend.id)
  File "/opt/odoo/addons/connector_prestashop/unit/importer.py", line 507, in import_batch
    return importer.run(filters=filters, **kwargs)
  File "/opt/odoo/addons/connector_prestashop/unit/importer.py", line 305, in run
    record_ids = self._run_page(filters, **kwargs)
  File "/opt/odoo/addons/connector_prestashop/unit/importer.py", line 313, in _run_page
    record_ids = self.backend_adapter.search(filters)
  File "/opt/odoo/addons/connector_prestashop/unit/backend_adapter.py", line 174, in search
    return self.client.search(self._prestashop_model, filters)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 521, in search
    PrestaShopWebServiceDict, self).search(resource, options=options)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 350, in search
    return self.get(resource, options=options)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 367, in get
    return self.get_with_url(full_url)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 540, in get_with_url
    response = super(PrestaShopWebServiceDict, self).get_with_url(url)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 375, in get_with_url
    return self._parse(self._execute(url, 'GET').content)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 616, in _parse
    parsed_content = super(PrestaShopWebServiceDict, self)._parse(content)
  File "/usr/local/lib/python2.7/dist-packages/prestapyt/prestapyt.py", line 244, in _parse
    (e, content[:512])
PrestaShopWebServiceError: 'HTTP XML response is not parsable : not well-formed (invalid token): line 48, column 105. <!DOCTYPE html>\n\n<html xmlns:fb="http://ogp.me/ns/fb#">\n<head>\n <meta content="text/html; charset=utf-8" http-equiv="Content-Type">\n <meta name="HandheldFriendly" content="True">\n <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">\n <meta name="format-detection" content="telephone=no">\n <meta property="robots" content="noindex,nofollow">\n\n <link type="text/css" rel="stylesheet" href="http://d2vdd8rzfx5'

**Comment by pedrobaeza** [comment]
Why do you repeat the exact same issue as #74?

**Comment by Stefano7777777** [comment]
beacuase was closed, i search a solution but i don't find any solution in whole google :(

**Comment by Stefano7777777** [comment]
please can you help me?

**Comment by pedrobaeza** [comment]
You can still reply on the closed issue, but nothing has changed: it's not a problem of this module. And sorry, I'm not able to help as I haven't faced that problem before.

**Comment by Stefano7777777** [comment]
sorry i don'ìt know that i can reply if it closed. ok thank'you

**Comment by witoszek** [comment]
I have the same error and I can not find any manual on this module. Ive do like  you say and nothing. Can you help me?,

**Comment by witoszek** [comment]
PrestaShopWebServiceError: 'HTTP XML response is not parsable : undefined entity: line 18, column 24. <!DOCTYPE html>\n\n\n\n\n<html lang="es">\n\t<head>\n\t\t<meta charset="utf-8">\n\n\t\t<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">\n\t\t<meta name="apple-mobile-web-app-capable" content="yes">\n\t\t<link rel='
