### ISSUE TITLE
export ERROR openerp.http: Exception during JSON

### ISSUE THREAD

**Issue by Stefano7777777** [OCA/connector-prestashop#79]
hi,

I know that I should study more, but since I managed to run almost all the import, 
I would have a mistake when I export a product to prestashop.
I installed connector_prestashop_catalog_manager without error but if I export a product created in odoo in the log file appear this error and obviously the file does not appear in prestashop, is it possible to know if it depends on some connector installation error?
ERROR Stanem openerp.http: Exception during JSON request handling.
Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 687, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 323, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 316, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 966, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 516, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/bus/controllers/main.py", line 34, in poll
    raise Exception("bus.Bus unavailable")
Exception: bus.Bus unavailable
2017-08-25 16:42:57,339 2100 INFO Stanem werkzeug: 127.0.0.1 - 17 16:42:57] "POST /longpolling/poll HTTP/1.1" 200 -

grazie

**Comment by guewen** [comment]
Hello,

This is unrelated to this project. This is a classical error in Odoo when you don't correctly configure the reverse proxy to redirect the longpolling url to the longpolling port. The only misbehavior in such case is that features using the longpolling such as the chat won't work and that logs are cluttered with this stacktrace. You should find explanations on that configuration with some research.
