### ISSUE TITLE
Odoo Server Error

### ISSUE THREAD

**Issue by anibalore** [OCA/connector-prestashop#87]
Hello
I'm trying to install the module but I have this error, I don't know what it means

Odoo Server Error
Traceback (most recent call last):
File "/odoo/odoo-server/openerp/http.py", line 650, in _handle_exception
return super(JsonRequest, self)._handle_exception(exception)
File "/odoo/odoo-server/openerp/http.py", line 687, in dispatch
result = self._call_function(**self.params)
File "/odoo/odoo-server/openerp/http.py", line 323, in _call_function
return checked_call(self.db, *args, **kwargs)
File "/odoo/odoo-server/openerp/service/model.py", line 118, in wrapper
return f(dbname, *args, **kwargs)
File "/odoo/odoo-server/openerp/http.py", line 316, in checked_call
result = self.endpoint(*a, **kw)
File "/odoo/odoo-server/openerp/http.py", line 966, in __call__
return self.method(*args, **kw)
File "/odoo/odoo-server/openerp/http.py", line 516, in response_wrap
response = f(*args, **kw)
File "/odoo/odoo-server/addons/web/controllers/main.py", line 899, in call_button
action = self._call_kw(model, method, args, {})
File "/odoo/odoo-server/addons/web/controllers/main.py", line 887, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/addons/base/module/module.py", line 459, in button_immediate_install
return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
File "/odoo/odoo-server/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/odoo/odoo-server/openerp/addons/base/module/module.py", line 534, in _button_immediate_function
registry = openerp.modules.registry.RegistryManager.new(cr.dbname, update_module=True)
File "/odoo/odoo-server/openerp/modules/registry.py", line 386, in new
openerp.modules.load_modules(registry._db, force_demo, status, update_module)
File "/odoo/odoo-server/openerp/modules/loading.py", line 340, in load_modules
loaded_modules, update_module)
File "/odoo/odoo-server/openerp/modules/loading.py", line 239, in load_marked_modules
loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
File "/odoo/odoo-server/openerp/modules/loading.py", line 132, in load_module_graph
models = registry.load(cr, package)
File "/odoo/odoo-server/openerp/modules/registry.py", line 169, in load
model = cls._build_model(self, cr)
File "/odoo/odoo-server/openerp/models.py", line 591, in _build_model
original_module = pool[name]._original_module if name in parents else cls._module
File "/odoo/odoo-server/openerp/modules/registry.py", line 84, in __getitem__
return self.models[model_name]
KeyError: 'base_multi_image.image'

**Comment by joserprieto** [comment]
What is your Odoo version?
OdooSA or OCB?
Repositories added?
Are you run the pip install requirements?

On the repository of branch 9.0 (latest stable):

https://github.com/OCA/connector-prestashop/tree/9.0

You can view two files:

https://github.com/OCA/connector-prestashop/blob/9.0/oca_dependencies.txt
https://github.com/OCA/connector-prestashop/blob/9.0/requirements.txt

This means that this repository has dependencies; in requeriments.txt, are the python modules dependencies; in this case:

```
html2text
prestapyt >= 0.7.0
unidecode
bs4
# tests dependencies
freezegun
vcrpy
```

so, once you have cloned / downloaded the repo, you have to install these requirements, with:

```
pip install requirements.txt 
```

And, we have to install the modules that are related on the oca_dependencies.txt:
```
connector
connector-ecommerce
e-commerce
product-attribute
product-variant
sale-workflow
```

The error can be related with the module "base_multi_image":

```
KeyError: 'base_multi_image.image'
```
https://github.com/OCA/server-tools/tree/10.0/base_multi_image

**Comment by flotho** [comment]
Hi @anibalore , could this one be closed ?
regards

**Comment by pedrobaeza** [comment]
Closing as bad deployment.
