### ISSUE TITLE
Error Product Export from Odoo 9 to Prestashop 1.6

### ISSUE THREAD

**Issue by ghost** [OCA/connector-prestashop#89]
Error:
Export a record on PrestaShop
UUID
65b7e007-c55a-429b-bf9b-6ca5ca2f004d
Aufgabe
openerp.addons.connector_prestashop.unit.exporter.export_record('prestashop.product.template', 1, {u'list_price': 1299})
Job-Funktion
openerp.addons.connector_prestashop.unit.exporter.export_record
Kanal
root.prestashop
Priorität
20
Ausführen nur nach

Benutzer-ID
Administrator

Anlagedatum
26.12.2017 23:07:57
Einreihungszeitpunkt
26.12.2017 23:07:58
Start Datum
26.12.2017 23:07:58
Erledigt am

Aktueller Versuch / Maximale Versuche 1 / 5 If the max. retries is 0, the number of retries is infinite.
Ausnahme Information
Traceback (most recent call last):
File "/opt/odoo_addons/shop_connect/connector/controllers/main.py", line 90, in runjob
self._try_perform_job(session_hdl, job)
File "/opt/odoo_addons/shop_connect/connector/controllers/main.py", line 66, in _try_perform_job
job.perform(session)
File "/opt/odoo_addons/shop_connect/connector/queue/job.py", line 493, in perform
self.result = self.func(session, *self.args, **self.kwargs)
File "/opt/odoo_addons/shop_connect/connector_prestashop/unit/exporter.py", line 352, in export_record
return exporter.run(binding_id, fields=fields, **kwargs)
File "/opt/odoo_addons/shop_connect/connector_prestashop/unit/exporter.py", line 52, in run
result = self._run(*args, **kwargs)
File "/opt/odoo_addons/shop_connect/connector_prestashop/unit/exporter.py", line 292, in _run
map_record = self._map_data()
File "/opt/odoo_addons/shop_connect/connector_prestashop/unit/exporter.py", line 221, in _map_data
return self.mapper.map_record(self.binding)
File "/opt/odoo_addons/shop_connect/connector_prestashop/unit/exporter.py", line 322, in mapper
TranslationPrestashopExportMapper)
File "/opt/odoo_addons/shop_connect/connector/connector.py", line 312, in get_connector_unit
self.model_name)(self)
File "/opt/odoo_addons/shop_connect/connector/backend.py", line 274, in get_class
(base_class, session, model_name, matching_classes))
AssertionError: Several classes found for <class 'openerp.addons.connector_prestashop.unit.mapper.TranslationPrestashopExportMapper'> with session <Session db_name: hk, uid: 1, context: {'job_uuid': u'65b7e007-c55a-429b-bf9b-6ca5ca2f004d'}>, model name: prestashop.product.template. Found: set([<class 'openerp.addons.connector_prestashop_catalog_manager.models.product_template.exporter.ProductTemplateExportMapper'>, <class 'openerp.addons.connector_prestashop_manufacturer.models.product_template.exporter.ProductTemplateExportMapper'>])

Second thing I found, the Product Images dont get Imported or Exported from an to Odoo.

The following of the descibed Functions don't Work:
Create/modify attributtes and values in Odoo and push then in PrestaShop.
Create/modify products and push them in PrestaShop.
Create/modify products variants and push them in PrestaShop (combinations).
Create/modify category and push them in PrestaShop.
Create/modify image and push then in PrestaShop.

This Issue schould only be closed if the Code Bug ist updated!

Pedro dont close cases if they havent been fixed yet. 

To all new Users, this Bug is Real and will stop you from Working with this Connector properly. Everyone should open an Issue!

**Comment by pedrobaeza** [comment]
I'm closing it because your insults. If this is a shit of code, why don't you bother?
